version: "3"

services:
  ########################################
  # gitlab
  ########################################
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url                          'http://gitlab.example.com:10080'
        gitlab_rails['gitlab_shell_ssh_port'] = 10022
        gitlab_rails['time_zone']             = 'Asia/Tokyo'
    ports:
      - '10080:10080'
      - '10022:22'
    volumes:
      - 'gitlab-data:/var/opt/gitlab'
      - 'gitlab-config:/etc/gitlab'
      - 'gitlab-log:/var/log/gitlab'

volumes:
  gitlab-data:
  gitlab-config:
  gitlab-log:
